# Generated by Django 4.2.6 on 2023-10-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_docker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RunDockerApp',
            new_name='RunDockerModel',
        ),
    ]
