# Generated by Django 4.2.6 on 2023-10-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_docker_app', '0002_rename_rundockerapp_rundockermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
