# Generated by Django 4.2.6 on 2023-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateDockerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('envs', models.JSONField()),
                ('command', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
